### ISSUE TITLE
router.js not found

### ISSUE THREAD

**Issue by AndrewKovalenko** [Daniel15/RouteJs#25]
I installed RouteJS MVC 4 package from nuget, after installation was done, I added 
`<script src="@RouteJs.RouteJsHandler.HandlerUrl"></script>`
to head section of _Layout.cshtml and run application.
After starting of application I got 
    `Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:50326/routejs.axd/49ba8976e3844742e2a86747a52c0d4d81ceab37/router.js`

**Comment by Daniel15** [comment]
Closing this out as it's stale now and it seems the latest issue is not related to RouteJs directly.
