### ISSUE TITLE
Build instructions are unclear

### ISSUE THREAD

**Issue by stijnherreman** [Daniel15/RouteJs#28]
I'm trying to build from source, but it seems to be more complicated than simply running `build.bat`.

- I'm running VS 2012, so I need to run a [previous version](https://github.com/Daniel15/RouteJs/blob/a15f923a08a08957d74d606ecdeac68586c31940/build.bat) of `build.bat`.
- I don't have a separate Git installation (using SourceTree with embedded Git), so I had to disable the `<GitVersion` part.
- There's no package restore done for `src\.nuget\packages.config` so *NUnit.Runners* is missing, making the build fail near the end.

**Comment by Daniel15** [comment]
Closing this since I haven't heard back, but please feel free to reopen if you're still encountering this issue. As I mentioned earlier, the build box is working properly, and that builds completely from scratch every time.
