### ISSUE TITLE
It returns null when the url is an empty string

### ISSUE THREAD

**Issue by hernangm** [Daniel15/RouteJs#37]
An empty string is a valid url resolvable from a route. However when finalUrl is an empty string, it returns null and it should return the empty string.

**Comment by Daniel15** [comment]
Just getting back into things now. Is an empty string really a valid URL? Wouldn't it be `/` for the root?

**Comment by hernangm** [comment]
Hi Daniel,

I have the following controller

    public class HomeController : Controller
    {
        [HttpGet, Route("")]
        public virtual ActionResult Index()
        {
            return View();
        }
    }

but when I call

Router.action("Home", "Index") in my js files I get some exception, although the route does exist in the list of registered routes as 

"{"route":{"url":"","defaults":{"controller":"Home","action":"Index"},"constraints":{},"optional":[]},"_params":[],"_parsedConstraints":{}}"

**Comment by Daniel15** [comment]
Good catch, thanks! I'll try to take a look soon.
