### ISSUE TITLE
Case sensitive constraint keys break with v1.1.8

### ISSUE THREAD

**Issue by boerbiet** [Daniel15/RouteJs#38]
Creating an issue from my comment, by request. 

I found out the change in 1.1.8 (Ignore case of controller, action, area, and keys of parameters) breaks some functionality on our site after a colleague updated from 1.1.7 to 1.1.8. For example:

C#
```
routes.MapRoute("Arbitrary Route", "path/{variableThing}/etc/", new { controller = "X", action = "Y" }, new { variableThing = "Z" });
```
JS
```
Router.Action('X', 'Y', { variableThing: 'Z' });
```
Now when the constraints are parsed, the key variable will be "variableThing". The objects however:
```
parsedConstraints['variableThing'] = /^(Z)/

routevalues['variablething'] = 'Z'
```
Due to the lower case key the route will not match.

**Comment by Daniel15** [comment]
Can you please try the latest build and let me know if it resolves your particular issue? You can get packages from the build server at http://teamcity.codebetter.com/viewLog.html?buildId=178515&tab=artifacts&buildTypeId=routejs&guest=1

**Comment by boerbiet** [comment]
I can confirm that the ajax controls that stopped working with 1.1.8 are working again with 1.1.9-dev.

**Comment by Daniel15** [comment]
Thanks for confirming!
