### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by chaddon** [Daniel15/RouteJs#39]
Hi,
When I add the following line to my Index.Mobile.cshtml

 script src="@RouteJs.RouteJsHandler.HandlerUrl"></script
(note: I removed the  script tags so the script shows in the comment, else it gets suppressed)

I get the warning "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/." in Google Chrome (Device emulation).

If I comment out the script, the warning goes away.
I am using jquery-2.1.1.min.js

Is this warning something I need to worry about? And is there a way to resolve this warning?

All the best,
Chris

**Comment by Daniel15** [comment]
Hmm, that is very strange. I don't think this is actually related to RouteJs, as it doesn't do any XMLHttpRequests at all.

**Comment by Daniel15** [comment]
I haven't been able to replicate this, please let me know if you're still seeing it and provide steps to replicate the issue. Thanks!
