### ISSUE TITLE
Area route with "area" in defaults throws exception

### ISSUE THREAD

**Issue by sn-tibi** [Daniel15/RouteJs#41]
My app routing works with no problems before adding RouteJs.
When I install RouteJs, the app crashes in the layout where I reference the script with src="@RouteJs.RouteJsHandler.HandlerUrl". The exception is "an item with the same key has already been added"

**Comment by sn-tibi** [comment]
forgot to mention that i use MVC4

**Comment by sn-tibi** [comment]
found the problem. if you use areas and register routes in a specific area and enter the default area in defaults for a specific route even though you implemented the AreaName getter, MVC will not break but RouteJs will. 

So if a route in an area is like this: context.MapRoute("routeName", "route/url/here", new { area = "areaName", controller = "controllerName", action = "actionName" }); RouteJs will break with the exception i mentioned. If you remove the area = "areaName" part works.

**Comment by Daniel15** [comment]
Ah, good catch. I think this probably shouldn't throw an exception. I'll reopen the task to remind myself to handle this better.
