### ISSUE TITLE
Mismatch between how attribute routes inside areas are matched

### ISSUE THREAD

**Issue by mrahhal** [Daniel15/RouteJs#48]
This is tested in AspNet5 only.

There's a mismatch between how mvc matches some of the routes inside an area that are specified with `RouteAttribute` and how the javascript route helper is matching them.

The repo that reproduces the issue is [here](https://github.com/mrahhal/RouteJsRepro). Basically this is what is happening:
![capture](https://cloud.githubusercontent.com/assets/4404199/11766633/08ac080c-a19a-11e5-9b3d-4745d5b2746c.PNG)

For some reason, mvc generates the following route for CategoriesController.Some:

``` json
{
        "precedence": 1.11,
        "order": 0,
        "url": "manage/Categories/some.call",
        "defaults": {
            "controller": "Categories",
            "action": "Some"
        },
        "constraints": {},
        "optional": []
    }
```

That's why routejs thinks it's an attribute route outside any area. I guess we expected mvc to include the`area` default also even if the route is attributed.

I'm not sure how we're supposed to solve this if mvc6 is not generating `area` default in this case. As it appears the logic of matching is not the same between mvc5/mvc6.

**Comment by Daniel15** [comment]
Thanks for the bug report, I'll try to take a look. The ASP.NET 5 support is pretty new, so I may have missed some edge cases.
