### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by roboriaan** [Daniel15/RouteJs#56]
Hi,

I'm trying to wire this up in asp.net core : SDK version : 1.0.0-preview2-003131
I'm getting :

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
>    at RouteJs.ServiceExtensions.AddRouteJs(IServiceCollection services, Action`1 configure)
>    at Core.Startup.ConfigureServices(IServiceCollection services)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by maria-negrea** [comment]
I have encountered the same issue, still haven't found a fix for that...

**Comment by Morten158** [comment]
Same here

**Comment by Daniel15** [comment]
I might need to update RouteJs for newer ASP.NET Core versions, it was last updated for RC2 a while back.

**Comment by Daniel15** [comment]
Please try version 2.2 and let me know if you still encounter issues. Thanks!
