### ISSUE TITLE
No updated RouteJs.AspNet nuget package for PR #53

### ISSUE THREAD

**Issue by steffes** [Daniel15/RouteJs#57]
PR #53 fixes many of the breaking changes in Core 1.1 since the May 2016 2.1.0 release. Will there be a nuget package update to RouteJs.AspNet or are there other issues that need to be addressed?

**Comment by Daniel15** [comment]
Sorry about that! I'll release an update soon.  In the meantime, you should be able to get the latest dev version from the build server's NuGet feed: https://ci.appveyor.com/nuget/routejs

**Comment by Daniel15** [comment]
Attribute routes aren't working on my test site, so I'm going to try and fix that before releasing an updated NuGet package.

**Comment by Daniel15** [comment]
Published as version 2.2.
